=== Ludovic-Lesur/HPGI/data/hikes/format.dtd
<!ELEMENT rando (nom, etape*)>

<!ELEMENT nom (#PCDATA)>

<!ELEMENT etape (heureDepart, ravitaillement, dejeuner, midi, soir, nuit, point*)>

<!ELEMENT heureDepart (#PCDATA)>
<!ELEMENT ravitaillement (#PCDATA)>
<!ELEMENT dejeuner (#PCDATA)>
<!ELEMENT soir (#PCDATA)>
<!ELEMENT nuit (#PCDATA)>

<!ELEMENT midi (lieu, repas)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT repas (#PCDATA)>

<!ELEMENT point (toponyme, pk, altitude, pause)>
<!ELEMENT toponyme (#PCDATA)>
<!ELEMENT pk (#PCDATA)>
<!ELEMENT altitude (#PCDATA)>
<!ELEMENT pause (#PCDATA)>

=== Ludovic-Lesur/HPGI/data/hikes/Trek_du_Col_des_Gentianes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rando SYSTEM "format.dtd">
<rando>
  <nom>Trek du Col des Gentianes</nom>
  <etape>
    <heureDepart>H13M30</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>R</dejeuner>
    <midi>
      <lieu>0</lieu>
      <repas>R</repas>
    </midi>
    <soir>R</soir>
    <nuit>R</nuit>
    <point>
      <toponyme>Parking de la Raillere</toponyme>
      <pk>0.0</pk>
      <altitude>1042</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pont_de_Benques</toponyme>
      <pk>0.3</pk>
      <altitude>1050</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Passerelle_du_Lutour</toponyme>
      <pk>0.6</pk>
      <altitude>1110</altitude>
      <pause>H0M5</pause>
    </point>
    <point>
      <toponyme>Intersection_GR10</toponyme>
      <pk>1.1</pk>
      <altitude>1200</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Le_Pradet</toponyme>
      <pk>1.6</pk>
      <altitude>1260</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Passerelle_d'Artigue</toponyme>
      <pk>2.2</pk>
      <altitude>1309</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>La_Fruitiere</toponyme>
      <pk>3.6</pk>
      <altitude>1371</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
  <etape>
    <heureDepart>H9M30</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>R</dejeuner>
    <midi>
      <lieu>2</lieu>
      <repas>R</repas>
    </midi>
    <soir>B</soir>
    <nuit>B</nuit>
    <point>
      <toponyme>La Fruitiere</toponyme>
      <pk>0.0</pk>
      <altitude>1371</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Refuge_d'Estom</toponyme>
      <pk>5.6</pk>
      <altitude>1804</altitude>
      <pause>H1M0</pause>
    </point>
    <point>
      <toponyme>Epaule_du_Labas</toponyme>
      <pk>8.4</pk>
      <altitude>2210</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Lac_d'Estom-Soubiran</toponyme>
      <pk>9.9</pk>
      <altitude>2360</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Lac_Couy</toponyme>
      <pk>10.4</pk>
      <altitude>2445</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Lac_Glace</toponyme>
      <pk>11.4</pk>
      <altitude>2565</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_des_Gentianes</toponyme>
      <pk>12.5</pk>
      <altitude>2729</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
  <etape>
    <heureDepart>H9M30</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>B</dejeuner>
    <midi>
      <lieu>3</lieu>
      <repas>B</repas>
    </midi>
    <soir>R</soir>
    <nuit>R</nuit>
    <point>
      <toponyme>Col des Gentianes</toponyme>
      <pk>0.0</pk>
      <altitude>2729</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Vallee_des_Oulettes</toponyme>
      <pk>1.9</pk>
      <altitude>2285</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Refuge_de_Bayssellance</toponyme>
      <pk>3.7</pk>
      <altitude>2651</altitude>
      <pause>H1M30</pause>
    </point>
    <point>
      <toponyme>Hourquette_d'Ossoue</toponyme>
      <pk>4.5</pk>
      <altitude>2734</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Refuge_des_Oulettes</toponyme>
      <pk>8.2</pk>
      <altitude>2151</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
  <etape>
    <heureDepart>H8M30</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>R</dejeuner>
    <midi>
      <lieu>6</lieu>
      <repas>R</repas>
    </midi>
    <soir>R</soir>
    <nuit>R</nuit>
    <point>
      <toponyme>Refuge des Oulettes</toponyme>
      <pk>0.0</pk>
      <altitude>2151</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Passerelle</toponyme>
      <pk>2.2</pk>
      <altitude>1980</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Cabane_du_Pinet</toponyme>
      <pk>4.1</pk>
      <altitude>1780</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Lac_de_Gaube</toponyme>
      <pk>4.7</pk>
      <altitude>1725</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Passerelle_de_Gaube</toponyme>
      <pk>5.6</pk>
      <altitude>1725</altitude>
      <pause>H0M30</pause>
    </point>
    <point>
      <toponyme>Pont_d'Espagne</toponyme>
      <pk>7.7</pk>
      <altitude>1496</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Pont_de_Bousses</toponyme>
      <pk>9.3</pk>
      <altitude>1380</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pont_du_Ceriset</toponyme>
      <pk>10.2</pk>
      <altitude>1263</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>La_Raillere</toponyme>
      <pk>12.2</pk>
      <altitude>1042</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
</rando>

=== Ludovic-Lesur/HPGI/data/hikes/Tour_de_la_Jordanne.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rando SYSTEM "format.dtd">
<rando>
  <nom>Tour_de_la_Jordanne</nom>
  <etape>
    <heureDepart>H9M0</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>R</dejeuner>
    <midi>
      <lieu>9</lieu>
      <repas>B</repas>
    </midi>
    <soir>B</soir>
    <nuit>B</nuit>
    <point>
      <toponyme>Mandailles</toponyme>
      <pk>0.0</pk>
      <altitude>924</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Le_Mas</toponyme>
      <pk>0.3</pk>
      <altitude>933</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Reservoir</toponyme>
      <pk>1.5</pk>
      <altitude>1105</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>D317</toponyme>
      <pk>2.6</pk>
      <altitude>1220</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Arete_du_Pertus</toponyme>
      <pk>4.0</pk>
      <altitude>1330</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_de_Ragouze</toponyme>
      <pk>5.0</pk>
      <altitude>1343</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_du_Gliziou</toponyme>
      <pk>6.2</pk>
      <altitude>1365</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_du_Griou</toponyme>
      <pk>8.8</pk>
      <altitude>1579</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Puy_Griou</toponyme>
      <pk>9.1</pk>
      <altitude>1690</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_du_Griou</toponyme>
      <pk>9.4</pk>
      <altitude>1579</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_de_Rombiere</toponyme>
      <pk>10.7</pk>
      <altitude>1525</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_de_Cabre</toponyme>
      <pk>12.1</pk>
      <altitude>1528</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Puy_de_Peyre_Arse</toponyme>
      <pk>13.2</pk>
      <altitude>1806</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
  <etape>
    <heureDepart>H7M0</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>B</dejeuner>
    <midi>
      <lieu>6</lieu>
      <repas>R</repas>
    </midi>
    <soir>R</soir>
    <nuit>R</nuit>
    <point>
      <toponyme>Puy de Peyre Arse</toponyme>
      <pk>0.0</pk>
      <altitude>1806</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>GR400</toponyme>
      <pk>1.2</pk>
      <altitude>1652</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Fours_de_Peyre_Arse</toponyme>
      <pk>1.8</pk>
      <altitude>1677</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Breche_de_Rolland</toponyme>
      <pk>2.3</pk>
      <altitude>1647</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Puy_Mary</toponyme>
      <pk>3.3</pk>
      <altitude>1783</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pas_de_Peyrol</toponyme>
      <pk>4.0</pk>
      <altitude>1588</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_de_Roche_Noire</toponyme>
      <pk>5.7</pk>
      <altitude>1531</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_de_Redondet</toponyme>
      <pk>6.4</pk>
      <altitude>1640</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Puy_Chavaroche</toponyme>
      <pk>7.4</pk>
      <altitude>1739</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_du_Piquet</toponyme>
      <pk>8.7</pk>
      <altitude>1541</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>La_Fumade_Vieille</toponyme>
      <pk>10.0</pk>
      <altitude>1173</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Lasteyrie</toponyme>
      <pk>11.0</pk>
      <altitude>989</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Mandailles</toponyme>
      <pk>11.6</pk>
      <altitude>924</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
</rando>

=== Ludovic-Lesur/HPGI/data/hikes/Boucle de Berniquaut.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rando SYSTEM "format.dtd">
<rando>
  <nom>Boucle de Berniquaut</nom>
  <etape>
    <heureDepart>H8M0</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>R</dejeuner>
    <midi>
      <lieu>13</lieu>
      <repas>B</repas>
    </midi>
    <soir>B</soir>
    <nuit>R</nuit>
    <point>
      <toponyme>Sorreze</toponyme>
      <pk>0.0</pk>
      <altitude>267</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Cimetiere</toponyme>
      <pk>0.9</pk>
      <altitude>284</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Roc_de_la_Fendeille</toponyme>
      <pk>2.7</pk>
      <altitude>542</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Cote_537m</toponyme>
      <pk>3.5</pk>
      <altitude>537</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Aven_de_Polypheme</toponyme>
      <pk>4.2</pk>
      <altitude>490</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Grotte_du_Calel</toponyme>
      <pk>4.6</pk>
      <altitude>525</altitude>
      <pause>H0M5</pause>
    </point>
    <point>
      <toponyme>Carriere</toponyme>
      <pk>5.3</pk>
      <altitude>540</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Intersection</toponyme>
      <pk>5.6</pk>
      <altitude>515</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pistre</toponyme>
      <pk>5.8</pk>
      <altitude>558</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Le_Castelet</toponyme>
      <pk>6.6</pk>
      <altitude>635</altitude>
      <pause>H0M5</pause>
    </point>
    <point>
      <toponyme>Relais_de_Trinquebise</toponyme>
      <pk>7.1</pk>
      <altitude>680</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Ruisseau_d'Orival</toponyme>
      <pk>7.6</pk>
      <altitude>660</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Chapelle_de_Saint-Jammes</toponyme>
      <pk>8.0</pk>
      <altitude>690</altitude>
      <pause>H1M0</pause>
    </point>
    <point>
      <toponyme>Cote_689m</toponyme>
      <pk>8.6</pk>
      <altitude>689</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Cote_688m</toponyme>
      <pk>8.9</pk>
      <altitude>688</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Cote_672m</toponyme>
      <pk>9.7</pk>
      <altitude>672</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Le_Montagnet</toponyme>
      <pk>11.0</pk>
      <altitude>690</altitude>
      <pause>H0M5</pause>
    </point>
    <point>
      <toponyme>jacournassy</toponyme>
      <pk>11.6</pk>
      <altitude>645</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Peyra_Ficada</toponyme>
      <pk>13.2</pk>
      <altitude>550</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col</toponyme>
      <pk>13.6</pk>
      <altitude>545</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Oppidum_de_Berniquaut</toponyme>
      <pk>14.0</pk>
      <altitude>568</altitude>
      <pause>H1M0</pause>
    </point>
    <point>
      <toponyme>Cote_395m</toponyme>
      <pk>15.5</pk>
      <altitude>395</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Saint_Alby</toponyme>
      <pk>16.5</pk>
      <altitude>292</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Sorreze</toponyme>
      <pk>17.1</pk>
      <altitude>267</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
</rando>

=== Ludovic-Lesur/HPGI/data/hikes/Tour_du_Caroux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rando SYSTEM "format.dtd">
<rando>
  <nom>Tour_du_Caroux</nom>
  <etape>
    <heureDepart>H8M0</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>R</dejeuner>
    <midi>
      <lieu>9</lieu>
      <repas>B</repas>
    </midi>
    <soir>B</soir>
    <nuit>B</nuit>
    <point>
      <toponyme>Pont_d'HÃ©ric</toponyme>
      <pk>0.0</pk>
      <altitude>154</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pont_ferroviaire</toponyme>
      <pk>0.9</pk>
      <altitude>160</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Le_Verdier_Haut</toponyme>
      <pk>1.3</pk>
      <altitude>200</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pont_du_Rieu-Tort</toponyme>
      <pk>2.5</pk>
      <altitude>290</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pont_du_Cerisier</toponyme>
      <pk>3.4</pk>
      <altitude>329</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Heric</toponyme>
      <pk>5.9</pk>
      <altitude>511</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Antecime</toponyme>
      <pk>6.2</pk>
      <altitude>580</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_du_Salis</toponyme>
      <pk>8.4</pk>
      <altitude>754</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_de_Liousses</toponyme>
      <pk>9.8</pk>
      <altitude>931</altitude>
      <pause>H1M0</pause>
    </point>
    <point>
      <toponyme>Col_de_l'Airole</toponyme>
      <pk>10.5</pk>
      <altitude>946</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Douch</toponyme>
      <pk>10.9</pk>
      <altitude>897</altitude>
      <pause>H0M5</pause>
    </point>
    <point>
      <toponyme>Cote_918m</toponyme>
      <pk>11.4</pk>
      <altitude>918</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Cote_1036m</toponyme>
      <pk>12.7</pk>
      <altitude>1036</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_d'Alingri</toponyme>
      <pk>13.1</pk>
      <altitude>1063</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Tour_du_Caroux</toponyme>
      <pk>13.5</pk>
      <altitude>1091</altitude>
      <pause>H0M30</pause>
    </point>
    <point>
      <toponyme>Col_d'Alingri</toponyme>
      <pk>13.9</pk>
      <altitude>1063</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Intersection_GR7</toponyme>
      <pk>14.8</pk>
      <altitude>1055</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Rieu_Tort</toponyme>
      <pk>16.2</pk>
      <altitude>970</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Plo_de_la_Maurelle</toponyme>
      <pk>16.6</pk>
      <altitude>1055</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Refuge_de_Font_Salesse</toponyme>
      <pk>16.9</pk>
      <altitude>1045</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
  <etape>
    <heureDepart>H7M0</heureDepart>
    <ravitaillement>0</ravitaillement>
    <dejeuner>B</dejeuner>
    <midi>
      <lieu>17</lieu>
      <repas>B</repas>
    </midi>
    <soir>R</soir>
    <nuit>R</nuit>
    <point>
      <toponyme>Refuge_de_Font_Salesse</toponyme>
      <pk>0.0</pk>
      <altitude>1045</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Table_d'orientation</toponyme>
      <pk>0.8</pk>
      <altitude>1037</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Intersection_1062m</toponyme>
      <pk>1.4</pk>
      <altitude>1062</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Plo_de_l'Aygue</toponyme>
      <pk>1.9</pk>
      <altitude>1056</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Jasse_de_Joucla</toponyme>
      <pk>2.5</pk>
      <altitude>1050</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Intersection_1047m</toponyme>
      <pk>3.3</pk>
      <altitude>1047</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Cote_1033m</toponyme>
      <pk>3.8</pk>
      <altitude>1033</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Bel_Plo</toponyme>
      <pk>4.6</pk>
      <altitude>980</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Intersection</toponyme>
      <pk>4.8</pk>
      <altitude>955</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Ruisseau_de_la_Combe</toponyme>
      <pk>5.6</pk>
      <altitude>1000</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Intersection_996m</toponyme>
      <pk>6.2</pk>
      <altitude>996</altitude>
      <pause>H0M10</pause>
    </point>
    <point>
      <toponyme>Intersection_595m</toponyme>
      <pk>7.6</pk>
      <altitude>595</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Col_de_la_Pomarede</toponyme>
      <pk>8.1</pk>
      <altitude>503</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Reservoir</toponyme>
      <pk>9.3</pk>
      <altitude>320</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Stele</toponyme>
      <pk>10.0</pk>
      <altitude>232</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>La_Coste</toponyme>
      <pk>10.6</pk>
      <altitude>235</altitude>
      <pause>H0M0</pause>
    </point>
    <point>
      <toponyme>Pont_d'Heric</toponyme>
      <pk>12.0</pk>
      <altitude>154</altitude>
      <pause>H0M0</pause>
    </point>
  </etape>
</rando>
